Models/MyCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NovelStore.Models
{
    public class MyCart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        public virtual void AddItem(Novel novel, int quantity)
        {
            CartLine line = Lines
            .Where(b => b.Novel.NovelId == novel.NovelId)
            .FirstOrDefault();
            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Novel = novel,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        public virtual void RemoveLine(Novel novel) =>
        Lines.RemoveAll(l => l.Novel.NovelId == novel.NovelId);
        public decimal ComputeTotalValue() =>
        Lines.Sum(e => e.Novel.Price * e.Quantity);
        public virtual void Clear() => Lines.Clear();
    }
    public class CartLine
    {
        public int CartLineID { get; set; }
        public Novel Novel{ get; set; }
        public int Quantity { get; set; }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NovelStore.Models;
namespace NovelStore.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private MyCart cart;
        public OrderController(IOrderRepository repoService, MyCart cartService)
        {
            repository = repoService;
            cart = cartService;
        }
        public ViewResult Checkout() => View(new Order());
        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                order.Lines = cart.Lines.ToArray();
                repository.SaveOrder(order);
                cart.Clear();
                return RedirectToPage("/Completed", new { orderId = order.OrderID });
            }
            else
            {
                return View();
            }
        }
    }
}

Pages/MyCart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NovelStore.MyTagHelper;
using NovelStore.Models;
using System.Linq;

namespace NovelStore.Pages
{
    public class MyCartModel : PageModel
    {
        private INovelStoreRepository repository;
        public MyCartModel(INovelStoreRepository repo, MyCart myCartService)
        {
            repository = repo;
            myCart = myCartService;
        }
        public MyCart myCart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long novelId, string returnUrl)
        {
            Novel novel = repository.Novels
            .FirstOrDefault(b => b.NovelId == novelId);
            myCart.AddItem(novel, 1);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long novelId, string returnUrl)
        {
            myCart.RemoveLine(myCart.Lines.First(cl =>
            cl.Novel.NovelId == novelId).Novel);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }

}

Pages/_MyCartLayout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NovelStore.Pages
{
    public class _MyCartLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/_ViewImports.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NovelStore.Pages
{
    public class _ViewImportsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/_ViewStart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NovelStore.Pages
{
    public class _ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Completed.cshtml
@page
<div class="text-center">
    <h3>Cảm ơn bạn đã đặt hàng của chúng tôi #@OrderId</h3>
    <p>Chúng tôi sẽ gửi hàng cho bạn trong thời gian sớm nhất.</p>
    <a class="btn btn-info" asp-controller="Home">Quay Lại Store</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string OrderId { get; set; }
}

Pages/MyCart.cshtml
@page
@model MyCartModel
<h2>Giỏ Hàng</h2>
<table class="table table-bordered">
    <thead class="thead-light">
        <tr>
            <th>Số lượng</th>
            <th>Tiểu thuyết</th>
            <th class="text-right">Giá Tiền</th>
            <th class="text-right">Tổng Phụ</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.myCart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Novel.Title</td>
            <td class="text-right">@line.Novel.Price.ToString("c")</td>
            <td class="text-right">
                @((line.Quantity * line.Novel.Price).ToString("c"))
            </td>
            <td class="text-center">
                <form asp-page-handler="Remove" method="post">
                    <input type="hidden" name="NovelId"
                           value="@line.Novel.NovelId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Remove
                    </button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Tổng Tiền:</td>
            <td class="text-right">
                @Model.myCart.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-info" href="@Model.ReturnUrl">Tiếp tục mua sắm</a>
    <a class="btn btn-info" asp-action="Checkout" asp-controller="Order">
        Thanh Toán
    </a>
</div>

Pages/_MyCartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Novel Store</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">NOVEL STORE</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>